# Generated by Django 5.1.4 on 2025-01-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_player_avatar_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
