# Generated by Django 5.1.4 on 2025-01-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_player_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='pong_player',
        ),
    ]
