
services:
  user_managment:
    build:
      context: ./backend/backend_services/user_managment
      dockerfile: Dockerfile
    container_name: user_managment
    env_file:
      - ./backend/backend_services/user_managment/.env
    ports:
      - "8000:8000"
    volumes:
      - private_key:/app/private_key
      - public_key:/app/public_key
      - logs:/app/logs
      - profile_images:/app/profile_images
  profile:
    build:
      context: ./backend/backend_services/profile
      dockerfile: Dockerfile
    container_name: profile
    env_file:
      - ./backend/backend_services/profile/.env
    ports:
      - "8001:8001"
    volumes:
      - public_key:/app/public_key
      - logs:/app/logs
      - profile_images:/app/profile_images











  database:
    image: postgres:latest
    container_name: database
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/db_data
  private_key:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/RSA-key/private
  public_key:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/RSA-key/public
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/logs
  profile_images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoss/ft_transcendence/others/profile_images