# Generated by Django 5.1.4 on 2025-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('received_id', models.IntegerField()),
                ('status', models.CharField(choices=[('FR', 'friends'), ('PN', 'pending'), ('BL', 'blocked')], default='PN', max_length=2)),
            ],
            options={
                'db_table': 'pong_friendship',
            },
        ),
    ]
