# Generated by Django 5.1.5 on 2025-01-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('BL', 'blocked'), ('PN', 'pending'), ('FR', 'friends')], default='PN', max_length=2),
        ),
    ]
