# Generated by Django 5.1.4 on 2025-01-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
